spring.application.name=site

langchain4j.open-ai.chat-model.api-key=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
langchain4j.open-ai.chat-model.model-name=gpt-4o
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
