spring.application.name=site

langchain4j.open-ai.chat-model.api-key=COLOCAR_CHAVE_AQUI
langchain4j.open-ai.chat-model.model-name=gpt-4o
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
